### ISSUE TITLE
unbind

### ISSUE THREAD

**Issue by liamgilbey** [liamgilbey/ldapr#1]
Unbind is returning errors about memory limits:

```r
Error: C stack usage  7971060 is too close to the limit
```

**Comment by nperp** [comment]
Hi @liamgilbey, 

although this is a 2 years old issue, I tried to fix the issue as I used your package,

I believe that the errors about memory limits, is just the typo of the function that is run when `l$unbind()` is run...  

I would appreciate if you could review my change and let me know if it works for you #2.

Cheers,
nperp

**Comment by liamgilbey** [comment]
Thanks for the PR - that seemed to do the trick nicely.

I also made the `search` method a little more fool-proof, so it will not crash R if you have successfully unbound from the LDAP server.
